config/routes.rb
Rails.application.routes.draw do
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   devise_for :users

   root to: 'pages#home'

   get 'dashboard', to: 'dashboard#index'
   resources :rooms, only: :update

   resources :rooms, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
     resources :reservation, only: [ :new, :create, :show ]
     resources :reviews, only: [ :new, :create, :show ]
   end

   resources :reservations, only: [ :show ]

end

#Rails.application.routes.draw do
  #devise_for :users
  #root to: "pages#home"
  #ressources :rooms,

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Route for new user registration
  #get '/users/new', to: 'users#new', as: 'new_user'
  #post '/users', to: 'users#create'

  # Routes for user login and logout
  #get '/login', to: 'sessions#new'
  #post '/login', to: 'sessions#create'
  #get '/logout', to: 'sessions#destroy'

  # Route for creating a new room
  #get '/rooms/new', to: 'rooms#new'
  #post '/rooms', to: 'rooms#create'

  # Route for showing a specific room
  #get '/rooms/:id', to: 'rooms#show', as: 'room'

  # Routes for creating a new reservation
  #get '/rooms/:id/reservations/new', to: 'reservations#new'
  #post '/rooms/:id/reservations', to: 'reservations#create'

  # Route for creating a review for a reservation
  #post '/reservations/:id/reviews', to: 'reviews#create'

  # Route for showing a specific user
  #get '/users/:id', to: 'users#show', as: 'user'

  # Route for showing reviews of a specific user
  #get '/users/:id/reviews', to: 'reviews#index'

  # Route for creating a new review for a reservation
  #get '/reservations/:id/reviews/new', to: 'reviews#new'

  # Defines the root path route ("/")
  # root "articles#index"
#end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_one :review

  validates :check_in_date, :check_out_date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  has_one :user, through: :reservations
  has_one :room, through: :reservations
  belongs_to :reservation

  validates :rating, :comment, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  geocoded_by :address

  # TODO: make an alias for user => should be "owner"
  # belongs_to :owner, class_name: "User"
  include PgSearch
  pg_search_scope :search_by_title_and_address,
    against: [ :title, :description, :address ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  belongs_to :user, foreign_key: 'users_id'
  has_many :bookings
  has_many :reviews

  after_validation :geocode, if: :will_save_change_to_address?



  def to_param
    id.to_s
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :rooms
  has_many :reservations
  has_many :reviews, through: :reservations
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :email, :encrypted_password, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index

    if params[:query].present?
      @rooms = policy_scope(Room).search_by_title_and_address(params[:query])
    else
      @rooms = policy_scope(Room)
      authorize @rooms
    end
    @markers = @rooms.where.not(latitude: nil, longitude: nil).map do |room|
      {
        lat: room.latitude,
        lng: room.longitude
        # infoWindow: { content: render_to_string(partial: "/boats/map_box", locals: { boat: boat }) }
      }
    end
  end

  def show
    @review = Review.new
    @reservation = Reservation.new
  end

  def new
    @room = Room.new
    authorize @room
  end

  def create
    @room = Room.new(room_params)
    @room.user = current_user
    authorize @room
    if @room.save
      redirect_to room_path(@room)
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @room.update(room_params)
      redirect_to room_path(@room)
    else
      render :edit
    end
  end

  def destroy
    if @room.destroy
      redirect_to rooms_path(@room)
    else
      render :index
    end
  end

  private

  def set_room
    @room = Room.find(params[:id])
    authorize @room
  end

  def room_params
    params[:room].permit(:title, :price, :description, :available_start_date, :available_end_date, :address)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  include Pundit
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = Room.all
  end

  def show
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user = current_user
    if @room.save
      redirect_to rooms_path(@room)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update(room_params)
      redirect_to room_path(@room)
    else
      render :edit
    end
  end

  def destroy
    if @room.destroy
      redirect_to rooms_path(@rooms)
    else
      render :index
    end
  end

  private

  def set_room
  @room = Room.all
  end

  def room_params
    params[:room].permit(:user, :user_id, :city, :neighborhood, :room_number, :bathroom_number, :bed_number, :max_ccupants, :price, :room_pictures, :available_start_date, :available_end_date, :title, :description)
  end
end




  ## GET /rooms
  ##def index
    ## @rooms = Room.all
  ##end

  # GET /rooms/new
  ##def new
    ##@room = Room.new
  ##end

  # POST /rooms
  ##def create
   ## @room = Room.new(room_params)

   ## if @room.save
     ## redirect_to @room, notice: 'Room was successfully created.'
   ## else
     ## render :new
   ## end
  ##end

  # GET /rooms/:id
  ##def show
  #### @room = Room.find(params[:id])
  ##end

  # PATCH/PUT /rooms/:id
  ##def update
  ##  @room = Room.find(params[:id])

    ##if @room.update(room_params)
     ## redirect_to @room, notice: 'Room was successfully updated.'
   ## else
    ##  render :edit
    ##end
  ##end

  # DELETE /rooms/:id
  ##def destroy
   ## @room = Room.find(params[:id])
   ## @room.destroy

   ## redirect_to rooms_url, notice: 'Room was successfully destroyed.'
  ##end

  ####end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StayFlex</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag 'application', 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
  </head>

  <body>
    <%= render "shared/navbar"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body> 
</html>

app/views/pages/_cards.html.erb
<section class="Home__cards">
  <div class="container">
    <h2 class="Home__cards-heading">Recently Added Boats</h2>
    <div class="row">
      <% @rooms.each do |room| %>
        <div class="col-sm-6 col-md-4">
          <%= render 'shared/card', room: room %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/reservations/show.html.erb
<div class="container-listing">
  <div class="row listing-content">
    <!-- Details box -->
    <div class="listing col-md-8">
      <div class="listing-title">
        <h3><strong><%= @room.title %></strong></h3>
        <p><%= @room.address %></p>
      </div><br>

      <div class="listing-details">
        <div class="row-content">
          <div class="col-xs-3">
            <p><strong>Highlights</strong></p>
          </div>

          <div class="col-xs-9">
              <%= @room.description %>
          </div>
        </div>
        <br><br>
      </div>

      <div class="listing-reviews">
        <%= render 'reviews' %>
      </div>
    </div>

    <%= render 'reservations/form', room: @room, reservation: @reservation %>

    <br><br><br>
  </div>

</div>

app/views/rooms/edit.html.erb
<h1>Edit Room</h1>

<%= form_with model: @room, url: room_path(@room), method: :patch do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <%= form.submit "Update Room" %>
<% end %>

<p><%= link_to "Back to Room", room_path(@room) %></p>

app/views/rooms/index.html.erb
<div class="container">
  <h1>Flats available in "athens"</h1>
</div>

<div class="container">

  <div class="d-flex justify-content-around">

    <div class="card-flat" class="pt-5" class="mw-100" class="mh-100">
      <img src="https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/296470766.jpg?k=ad01a76e86799cb27e099b8db5e4e5d1506a9184ebaa74c225a6b477fbad87e7&o=" />
        <div class="card-flat-infos">
          <div>
            <h2>Lovely flat in Athens</h2>
              <p>Flat with a view into the Acropole</p>
          </div>
          <h2 class="card-flat-pricing">199.99€</h2>
          <img src="https://www.pngmart.com/files/21/Account-User-PNG-Clipart.png" class="card-flat-user avatar-bordered" />
        </div>
        <div class="container">
        <div class="d-flex justify-content-around"><div><%= link_to "View more", "/rooms/:id", class: "btn btn-flat" %></div></div>
        </div>
    </div>

    <div class="card-flat" class="pt-5" class="mw-100" class="mh-100">
      <img src="https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/296470766.jpg?k=ad01a76e86799cb27e099b8db5e4e5d1506a9184ebaa74c225a6b477fbad87e7&o=" />
        <div class="card-flat-infos">
          <div>
            <h2>Lovely flat in Athens</h2>
              <p>Flat with a view into the Acropole</p>
          </div>
          <h2 class="card-flat-pricing">199.99€</h2>
          <img src="https://www.pngmart.com/files/21/Account-User-PNG-Clipart.png" class="card-flat-user avatar-bordered" />
        </div>
        <div class="container">
        <div class="d-flex justify-content-around"><div><%= link_to "View more", "#", class: "btn btn-flat" %></div></div>
        </div>
    </div>

    <div class="card-flat" class="pt-5" class="mw-100" class="mh-100">
      <img src="https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/296470766.jpg?k=ad01a76e86799cb27e099b8db5e4e5d1506a9184ebaa74c225a6b477fbad87e7&o=" />
        <div class="card-flat-infos">
          <div>
            <h2>Lovely flat in Athens</h2>
              <p>Flat with a view into the Acropole</p>
          </div>
          <h2 class="card-flat-pricing">199.99€</h2>
          <img src="https://www.pngmart.com/files/21/Account-User-PNG-Clipart.png" class="card-flat-user avatar-bordered" />
        </div>
        <div class="container">
        <div class="d-flex justify-content-around"><div><%= link_to "View more", "#", class: "btn btn-flat" %></div></div>
        </div>
    </div>

    <div class="card-flat" class="pt-5" class="mw-100" class="mh-100">
      <img src="https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/296470766.jpg?k=ad01a76e86799cb27e099b8db5e4e5d1506a9184ebaa74c225a6b477fbad87e7&o=" />
        <div class="card-flat-infos">
          <div>
            <h2>Lovely flat in Athens</h2>
              <p>Flat with a view into the Acropole</p>
          </div>
          <h2 class="card-flat-pricing">199.99€</h2>
          <img src="https://www.pngmart.com/files/21/Account-User-PNG-Clipart.png" class="card-flat-user avatar-bordered" />
        </div>
        <div class="container">
        <div class="d-flex justify-content-around"><div><%= link_to "View more", "#", class: "btn btn-flat" %></div></div>
        </div>
    </div>
  </div>


<div class="container">

  <div class="d-flex justify-content-around">

    <div class="card-flat" class="pt-5" class="mw-100" class="mh-100">
      <img src="https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/296470766.jpg?k=ad01a76e86799cb27e099b8db5e4e5d1506a9184ebaa74c225a6b477fbad87e7&o=" />
        <div class="card-flat-infos">
          <div>
            <h2>Lovely flat in Athens</h2>
              <p>Flat with a view into the Acropole</p>
          </div>
          <h2 class="card-flat-pricing">199.99€</h2>
          <img src="https://www.pngmart.com/files/21/Account-User-PNG-Clipart.png" class="card-flat-user avatar-bordered" />
        </div>
        <div class="container">
        <div class="d-flex justify-content-around"><div><%= link_to "View more", "#", class: "btn btn-flat" %></div></div>
        </div>
    </div>

    <div class="card-flat" class="pt-5" class="mw-100" class="mh-100">
      <img src="https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/296470766.jpg?k=ad01a76e86799cb27e099b8db5e4e5d1506a9184ebaa74c225a6b477fbad87e7&o=" />
        <div class="card-flat-infos">
          <div>
            <h2>Lovely flat in Athens</h2>
              <p>Flat with a view into the Acropole</p>
          </div>
          <h2 class="card-flat-pricing">199.99€</h2>
          <img src="https://www.pngmart.com/files/21/Account-User-PNG-Clipart.png" class="card-flat-user avatar-bordered" />
        </div>
        <div class="container">
        <div class="d-flex justify-content-around"><div><%= link_to "View more", "#", class: "btn btn-flat" %></div></div>
        </div>
    </div>

    <div class="card-flat" class="pt-5" class="mw-100" class="mh-100">
      <img src="https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/296470766.jpg?k=ad01a76e86799cb27e099b8db5e4e5d1506a9184ebaa74c225a6b477fbad87e7&o=" />
        <div class="card-flat-infos">
          <div>
            <h2>Lovely flat in Athens</h2>
              <p>Flat with a view into the Acropole</p>
          </div>
          <h2 class="card-flat-pricing">199.99€</h2>
          <img src="https://www.pngmart.com/files/21/Account-User-PNG-Clipart.png" class="card-flat-user avatar-bordered" />
        </div>
        <div class="container">
        <div class="d-flex justify-content-around"><div><%= link_to "View more", "#", class: "btn btn-flat" %></div></div>
        </div>
    </div>

    <div class="card-flat" class="pt-5" class="mw-100" class="mh-100">
      <img src="https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/296470766.jpg?k=ad01a76e86799cb27e099b8db5e4e5d1506a9184ebaa74c225a6b477fbad87e7&o=" />
        <div class="card-flat-infos">
          <div>
            <h2>Lovely flat in Athens</h2>
              <p>Flat with a view into the Acropole</p>
          </div>
          <h2 class="card-flat-pricing">199.99€</h2>
          <img src="https://www.pngmart.com/files/21/Account-User-PNG-Clipart.png" class="card-flat-user avatar-bordered" />
        </div>
        <div class="container">
        <div class="d-flex justify-content-around"><div><%= link_to "View more", "#", class: "btn btn-flat" %></div></div>
        </div>
    </div>
  </div>


<div class="container">

  <div class="d-flex justify-content-around">

    <div class="card-flat" class="pt-5" class="mw-100" class="mh-100">
      <img src="https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/296470766.jpg?k=ad01a76e86799cb27e099b8db5e4e5d1506a9184ebaa74c225a6b477fbad87e7&o=" />
        <div class="card-flat-infos">
          <div>
            <h2>Lovely flat in Athens</h2>
              <p>Flat with a view into the Acropole</p>
          </div>
          <h2 class="card-flat-pricing">199.99€</h2>
          <img src="https://www.pngmart.com/files/21/Account-User-PNG-Clipart.png" class="card-flat-user avatar-bordered" />
        </div>
        <div class="container">
        <div class="d-flex justify-content-around"><div><%= link_to "View more", "#", class: "btn btn-flat" %></div></div>
        </div>
    </div>

    <div class="card-flat" class="pt-5" class="mw-100" class="mh-100">
      <img src="https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/296470766.jpg?k=ad01a76e86799cb27e099b8db5e4e5d1506a9184ebaa74c225a6b477fbad87e7&o=" />
        <div class="card-flat-infos">
          <div>
            <h2>Lovely flat in Athens</h2>
              <p>Flat with a view into the Acropole</p>
          </div>
          <h2 class="card-flat-pricing">199.99€</h2>
          <img src="https://www.pngmart.com/files/21/Account-User-PNG-Clipart.png" class="card-flat-user avatar-bordered" />
        </div>
        <div class="container">
        <div class="d-flex justify-content-around"><div><%= link_to "View more", "#", class: "btn btn-flat" %></div></div>
        </div>
    </div>

    <div class="card-flat" class="pt-5" class="mw-100" class="mh-100">
      <img src="https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/296470766.jpg?k=ad01a76e86799cb27e099b8db5e4e5d1506a9184ebaa74c225a6b477fbad87e7&o=" />
        <div class="card-flat-infos">
          <div>
            <h2>Lovely flat in Athens</h2>
              <p>Flat with a view into the Acropole</p>
          </div>
          <h2 class="card-flat-pricing">199.99€</h2>
          <img src="https://www.pngmart.com/files/21/Account-User-PNG-Clipart.png" class="card-flat-user avatar-bordered" />
        </div>
        <div class="container">
        <div class="d-flex justify-content-around"><div><%= link_to "View more", "#", class: "btn btn-flat" %></div></div>
        </div>
    </div>

    <div class="card-flat" class="pt-5" class="mw-100" class="mh-100">
      <img src="https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/296470766.jpg?k=ad01a76e86799cb27e099b8db5e4e5d1506a9184ebaa74c225a6b477fbad87e7&o=" />
        <div class="card-flat-infos">
          <div>
            <h2>Lovely flat in Athens</h2>
              <p>Flat with a view into the Acropole</p>
          </div>
          <h2 class="card-flat-pricing">199.99€</h2>
          <img src="https://www.pngmart.com/files/21/Account-User-PNG-Clipart.png" class="card-flat-user avatar-bordered" />
        </div>
        <div class="container">
        <div class="d-flex justify-content-around"><div><%= link_to "View more", "#", class: "btn btn-flat" %></div></div>
        </div>
    </div>
  </div>



  <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Stay Relax, Stay Flex
  </div>
</div>





<ul>
  <% @rooms.each do |room| %>
    <li>
      <%= link_to room.title, room %>
      <p><%= room.description %></p>
      <p><strong>Price:</strong> <%= room.price %></p>
    </li>
  <% end %>
</ul>

<%# <><%= link_to "Add a New Room", new_room_path #%>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= form_with model: @room, url: rooms_path do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <%= form.submit "Create Room" %>
<% end %>

<p><%= link_to "Back to Rooms", rooms_path %></p>

app/views/rooms/show.html.erb
<div class="container">
<h1>Lovely flat in Athens</h1>

</div>


<div class="container">
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/296470766.jpg?k=ad01a76e86799cb27e099b8db5e4e5d1506a9184ebaa74c225a6b477fbad87e7&o=);">
  <div class="container">
    <h1>Lovely flat in Athens</h1>
    <p>Next to the Acropole discover this secret place for your hollidays</p>
  </div>
</div>
</div>

<div class="container">
  <div class="d-flex justify-content-between">
  <img src="https://media-cdn.tripadvisor.com/media/vr-splice-j/06/68/f2/3c.jpg" alt="" width="250px">
  <img src="https://cf.bstatic.com/xdata/images/hotel/max1024x768/379399676.jpg?k=2b20b61b2f87af45e87274f21e61f7bbe15abe16207ae05e849377b02dc0c653&o=&hp=1" alt="" width="250px">
  <img src="https://cf.bstatic.com/xdata/images/hotel/max1024x768/107792866.jpg?k=5039faaa337073bdf75ededd544f5389aea3594066a6d0446c845c836e8858f6&o=&hp=1" alt="" width="250px">
  <img src="https://cf.bstatic.com/xdata/images/hotel/max1024x768/375022892.jpg?k=338ac5e22c3b2b64811760455f857f2170431d2069f5a7e04e504e0ed23c6835&o=&hp=1" alt="" width="250px">

  </div>
</div>

<div class="container">
<h2>Description</h2>
<p>A luxury place in Athens, next to the Acropol with a view on it. Enjoy the terrace with this view. Perfect for a small family who look for calm.</p>
<p>I'm a tour guide so I can give you tips on the city, know the best places. This flat is near to the best restaurant of Athens, and 15 minutes from the sea !</p>
</div>

<div class="container">
<h2>Know more about this flat</h2>
<div class="container">
<i class="fa fa-bed" aria-hidden="true"></i>
<p><strong>Number of bed(s): </strong>2 beds, perfect for a small family with 1 child</p>

<i class="fa fa-wifi" aria-hidden="true"></i>
<p><strong>Wi-fi</strong> available</p>

<i class="fa fa-check-square" aria-hidden="true"></i>
<p><strong>Available from</strong> 01/09/2023 <strong>to</strong> 01/10/2023</p>

<i class="fa-solid fa-users"></i>
<p><strong>Max occupants :</strong> 4 people</p>

</div>

</div>

<div class="container">
<div class="container" class="m-5">
<button type="button" class="m-5" class="p-5" class="btn btn-secondary">Secondary</button>

</div>

</div>

  <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Stay Relax, Stay Flex
  </div>
</div>

app/views/shared/_banner.html.erb
<section class="Banner">
    <div class="Banner__inner container">
      <div class="Banner__content">
        <h1 class="Banner__heading">Go everywhere you want to be.</h1>
        <p class="Banner__leading">Alone, with friends or love, it's up to you...</p>
        <%= form_tag('/rooms', method: "get", class: "Banner__form") do %>
          <div class="input-group input-group-lg">
            <%= text_field_tag(:query, nil, placeholder: "Type the city you want to go in...", class: "Input Banner__input form-control") %>
            <div class="input-group-btn">
              <%= button_tag :submit, class: "btn btn-primary btn-lg" do %>
                <i class="fa fa-search" aria-hidden="true"></i>
                <% link_to rooms_path %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
</section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<%# navbar %>

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://logodownload.org/wp-content/uploads/2016/10/airbnb-logo-0.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Accueil", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://www.pngmart.com/files/21/Account-User-PNG-Clipart.png", class: "avatar-bordered", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Add a room", new_room_path, class: "dropdown-item" %>
              <%= link_to "My rooms", rooms_path, class: "dropdown-item" %>
              <%= link_to "My reservations", '#', class: "dropdown-item" %>
              <%= link_to "Log out",  destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>